export const sectors: string[] = [
    'Aeropuetos',
    'Association',
    'Firma Architectura',
    'Hospitales',
    'Hotel',
    'Integración',
    'Mix Use',
    'Office Tower',
    'Operador',
    'Park / Other',
    'Parking Company',
    'Promotor/Desarrollador',
    'Real Estate / Constructora',
    'Retailer',
    'Shopping Malls',
    'Supermercados',
    'Supplier',
    'Universidades'
  ];
